### ISSUE TITLE
SSH Host Key Management

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#1]
Confidant should create and store SSH host keys for each IAM role, so that they can be used as stable keys for autoscale groups. Should be delivered from the get_service route (/v1/services/id). Maybe this should be opt-in per service. Should be configurable feature so that it can be disabled by default.

**Comment by smiller171** [comment]
This sounds great. I have been looking for a good way to handle auto-scaling an ssh jump host

**Comment by ryan-lane** [comment]
By using #31 we can make the implementation of this simpler. When a service is created in Confidant, we can record a normal secret that's simply shared with a service, but the client can decide where and how it's going to write the secret by inspecting the metadata.

**Comment by ryan-lane** [comment]
I think that using netflix bless, with some of Lyft's proposed changes is a better approach than managing the host keys in confidant:

https://github.com/Netflix/bless

Our changes add host key management, and certificate management, and use kmsauth.
