### ISSUE TITLE
Setting DEBUG to true does not cause app to log at debug level

### ISSUE THREAD

**Issue by egeland** [lyft/confidant#116]
I see in the code that there are several `logger.debug("<some message here>")` lines, which I'd expect to see output if I have the `DEBUG` environment variable set. This does not happen.

Is it something I'm possibly doing wrong, or should I try to put that into the code and provide a PR?

**Comment by ryan-lane** [comment]
If you have DEBUG=true, it should be showing the debug output. Which way are you installing/running confidant? It could be that gunicorn isn't outputting all the logs.

**Comment by egeland** [comment]
Running it in the Docker image (in k8s) - setting everything via env vars in the Deployment config.
I have
```
env:
  - name: DEBUG
    value: 'True'
```
(along with other setting not shown here)

**Comment by ryan-lane** [comment]
Do you see warnings, errors, info, or anything along those lines in your logs? I've had a hell of a time getting the logging to work consistently in docker, for some reason.

**Comment by egeland** [comment]
I've seen everything except debug level, I think - e.g:
```
[2017-02-07 22:21:16 +0000] [1] [INFO] Starting gunicorn 19.3.0
[2017-02-07 22:21:16 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2017-02-07 22:21:16 +0000] [1] [INFO] Using worker: gevent
[2017-02-07 22:21:16 +0000] [10] [INFO] Booting worker with pid: 10
[2017-02-07 22:21:16 +0000] [13] [INFO] Booting worker with pid: 13
WARNING:root:No saml_authn_request_id in session
10.44.13.129 - - [07/Feb/2017:22:22:37 +0000] "POST /v1/saml/consume HTTP/1.1" 401 169 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
```

**Comment by ryan-lane** [comment]
I'm betting the `--log-level` setting for gunicorn needs to be set to `debug`. I think you should be able to pass that in as an extra argument to the default command.
