### ISSUE TITLE
SAML_FAKE_HTTPS needs to be configurable without requiring debug mode

### ISSUE THREAD

**Issue by pavelnikolov** [lyft/confidant#126]
When we run Confidant using Kubernetes we have problems when the `SAML_FAKE_HTTPS` is set to `false`. We would like to set it to `true` without enabling debug mode. Otherwise we get this error:

```
{
  "errors": [
    "invalid_response"
  ], 
  "message": "SAML request failed", 
  "reason": "The response was received at http://XXXXX/saml/consume instead of https://XXXXX/saml/consume", 
  "request_id": null
}
```

**Comment by ryan-lane** [comment]
We only currently support SAML with https, as it's insecure without. Is this for testing purposes?

**Comment by pavelnikolov** [comment]
It's for production application deployed in Kubernetes. But I believe that any app with a reverse proxy in front of it would have the same problem..

**Comment by ryan-lane** [comment]
If you have a reverse proxy in front then X-Forwarded-Proto should solve your problem here. You need to set `--forwarded-allow-ips=*` for your gunicorn config for this, though; see https://github.com/lyft/confidant/issues/50

**Comment by ryan-lane** [comment]
Did this solve your issue? I really need to close out #50. Pretty frequent issue folks run into.

**Comment by egeland** [comment]
Yes, that fixes it - please make this the default in your docker image.

**Comment by ryan-lane** [comment]
In #50 I mentioned that we're recommending setting the FORWARDED_ALLOW_IPS environment var when running the docker image, because it's difficult to modify the setting if we set it by default in the image. We may followup later and have the docker image run a script as a command where we have a bit more flexibility in how we start the process in docker.
