### ISSUE TITLE
Does not run locally without setting AWS credentials

### ISSUE THREAD

**Issue by edify42** [lyft/confidant#150]
The docker-compose file uses a local DynamoDB running in a docker container to run Confidant.

The pynamodb library used to create the dynamodb table in the confidant app requires AWS credentials to be set in order to create the table as it tries to do some describe operations with table metadata but fails as no credentials are provided: 

```
confidant_1  |   File "/usr/local/lib/python2.7/dist-packages/pynamodb/connection/table.py", line 175, in query
confidant_1  |     select=select)
confidant_1  |   File "/usr/local/lib/python2.7/dist-packages/pynamodb/connection/base.py", line 1006, in query
confidant_1  |     tbl = self.get_meta_table(table_name)
confidant_1  |   File "/usr/local/lib/python2.7/dist-packages/pynamodb/connection/base.py", line 402, in get_meta_table
confidant_1  |     raise TableError("Unable to describe table: {0}".format(e), e)
confidant_1  | TableError: Unable to describe table: Unable to locate credentials
```

My service.env file is below which successfully runs Confidant locally as it sets the AWS key and secret values in the shell environment. These can be fake values as below:
```
AWS_DEFAULT_REGION=ap-southeast-2
USE_AUTH=false
USE_ENCRYPTION=false
SSLIFY=false
DYNAMODB_URL=http://dynamo:7777
DYNAMODB_CREATE_TABLE=true
DEBUG=true
DYNAMODB_TABLE=mytable
AWS_ACCESS_KEY_ID=fake
AWS_SECRET_ACCESS_KEY=key
```

Interestingly though the aws cli does not register any tables being available after I've exposed the port of the dynamodb docker image:
```
~ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                    NAMES
734b951ccfe9        lyft/confidant        "gunicorn confidan..."   11 minutes ago      Up 11 minutes       0.0.0.0:80->80/tcp       confidant_confidant_1
6baf3382ac36        redis                 "docker-entrypoint..."   11 minutes ago      Up 11 minutes       0.0.0.0:6379->6379/tcp   confidant_redis_1
851f28709b03        tray/dynamodb-local   "/opt/jdk/bin/java..."   11 minutes ago      Up 11 minutes       0.0.0.0:7777->7777/tcp   confidant_dynamo_1
~ aws dynamodb list-tables --endpoint-url http://localhost:7777
{
    "TableNames": []
}
```

**Comment by ryan-lane** [comment]
Hey @edify42. Local dynamo requires AWS credentials to be set to work. I'll update the docs to indicate this.

It's interesting that the table isn't created. What happens when you try to create credentials or services through the interface? I'll try to repro this locally.

**Comment by arjunblj** [comment]
I'm having this same issue; my AWS credentials are set up correctly locally. I get the output of:
```
~ aws dynamodb list-tables
{
    "TableNames": []
}
```
Running `aws dynamodb list-tables --endpoint-url http://localhost:7777` actually hangs and doesn't finish executing.

**Comment by edify42** [comment]
Closing as per @ryan-lane 's comment above.
