### ISSUE TITLE
Docker gunicorn process correctly starts up but doesn't run the app

### ISSUE THREAD

**Issue by arjunblj** [lyft/confidant#151]
Not sure if clone of #150.

I have local AWS credentials (in `~/.aws`) and the configuration variables passed to Docker via a CLI arg but nothing shows up when I navigate to the app's address. In addition, tables aren't created/there's nothing that indicates a running process. I run:

```sh
> docker run --env-file DOCKER_CONFIG -t lyft/confidant
```

What I see when I navigate to `http://0.0.0.0:80`:

![image](https://user-images.githubusercontent.com/1711143/30564237-646ac666-9c92-11e7-91bf-90042be28ce3.png)

Do the KMS master or auth keys have to be created manually in AWS' IAM in order to get this running?

Thank you!

**Comment by ryan-lane** [comment]
0.0.0.0 is what gunicorn listens on, to say "I'll accept traffic from any interface", but it's not what you want to visit to get to the service from your browser. You need to connect to the IP of the container. Docker makes this annoyingly difficult. First find the container:

```
docker ps
```

Then find the IP for the container, using its container id:

```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_id>
```

Then connect to that IP address.

**Comment by arjunblj** [comment]
Thanks @ryan-lane! The port that provided (`172.17.0.2`) still shows me the same page, on port 80/8000 as well. Not sure why this is.

**Comment by ryan-lane** [comment]
Are you using boot2docker, or virtualbox or some other thing? It's possible it's doing port mapping to the vm, then to docker. So it may be some other IP you need to hit... Does the output from docker compose say anything?

**Comment by arjunblj** [comment]
I'm not using boot2docker. When I tried `docker-compose`, I got the error:
```
ERROR: for dynamo  Cannot start service dynamo: Mounts denied:
The path /mnt/dynamo
```
After creating that directory, I'm getting
```sh
> getcwd() failed with errno 2/No such file or directory
```
on all my Docker commands.

**Comment by arjunblj** [comment]
Hey @ryan-lane -- thanks for your help earlier. I'm still having issues with this, would a more detailed trace be helpful?

**Comment by philipbjorge** [comment]
@arjunblj -- how'd you resolve this?
