### ISSUE TITLE
Confidant strips newlines when submitting credentials through webpage

### ISSUE THREAD

**Issue by caedus41** [lyft/confidant#156]
We're using Confidant to store, among other things, our certificates. When making requests between our machines we noticed that they were failing due to a SSL certificate verification error. Through some investigation, I found that the md5sum of the certificate is different after it's been sent through Confidant. 

It seems like this is caused by the angular.js frontend, which I believe is stripping off newlines. I tried pasting in a value with a newline at the end, confirmed that the blank line was there after pasting, and found it to be missing when editing the credential again after saving.

I then tried to edit the value by adding newlines and noticed that the textarea class is still marked as "ng-pristine". After adding alphabetical characters, you can see that "ng-pristine" is removed and "ng-dirty" is added to the textarea class. I've pasted images below showing the three states, where the textarea has not been edited, a newline has been added but the area is still marked as pristine, and then with text added and the area marked as dirty. 

For reference, we're running Confidant version 1.1.13. 

![image](https://user-images.githubusercontent.com/8161667/32189653-c8664acc-bd81-11e7-88cb-de4fef8d1199.png)

![image](https://user-images.githubusercontent.com/8161667/32189689-e031102e-bd81-11e7-95b1-9078002e1b62.png)

![image](https://user-images.githubusercontent.com/8161667/32189702-edb6739c-bd81-11e7-89c7-abc86a4b6ddd.png)

**Comment by ryan-lane** [comment]
Hm. Interesting. I'll try to reproduce.

**Comment by ryan-lane** [comment]
Yep. I've reproduced this. Let me try to get a fix in.

**Comment by ryan-lane** [comment]
Hm. Github auto-closed this issue. I'm releasing this as 1.10.1. I'll let you know when it's released so you can give it a try.

**Comment by ryan-lane** [comment]
Ok. 1.10.1 is released on dockerhub, and pypi. There shouldn't be any breaking changes between your version and this version, so it should be safe to upgrade.

**Comment by ryan-lane** [comment]
If things aren't fixed, I'll reopen the issue :)
