### ISSUE TITLE
issue with SAML

### ISSUE THREAD

**Issue by JoshuaSeidel** [lyft/confidant#162]
"errors": [
    "invalid_response"
  ], 
  "message": "SAML request failed", 
  "reason": "There is no AttributeStatement on the Response", 
  "request_id": null
}

**Comment by vivianho** [comment]
@JoshuaSeidel the error you are getting is here: https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L178-L182

You need to set `SAML_WANT_ATTRIBUTE_STATEMENT` to `False` (https://github.com/lyft/confidant/blob/master/confidant/settings.py#L179)

**Comment by JoshuaSeidel** [comment]
@vivianho now it just hangs

 2017-12-07 15:08:30[2017-12-07 20:08:30 +0000] [1] [INFO] Starting gunicorn 19.7.1
[2017-12-07 20:08:30 +0000] [1] [INFO] Starting gunicorn 19.7.1

**Comment by JoshuaSeidel** [comment]
never mind seemed to work

**Comment by ryan-lane** [comment]
Awesome. Glad to see that's working. We'll put this error into an FAQ.
