### ISSUE TITLE
More Webhook support

### ISSUE THREAD

**Issue by edify42** [lyft/confidant#186]
The current design only allows for 1 webhook endpoint to be configured (with basic authentication supported).

I'd like to extend this by allowing 1 extra environment variable to be injected `WEBHOOK_ARRAY_FILE` which points to a JSON file with data that looks like below:

```
[
  {
    "WEBHOOK_URL": "https://webhook_dev.example.com"
  },
  {
    "WEBHOOK_URL": "https://webhook_test.example.com",
    "WEBHOOK_USERNAME": "myhookuser",
    "WEBHOOK_PASSWORD": "mylongandsupersecurehookpassword"
  }
]
```

This file can be mounted onto the docker container and the path passed in via `WEBHOOK_ARRAY_FILE`. The existing functionality will not be broken and users can now add multiple webhook endpoints when secrets are updated.

**Comment by edify42** [comment]
@ryan-lane is this something we could do?

I saw the issue @egeland raised with Webhooks regarding security

**Comment by ryan-lane** [comment]
Hey! Let me take a look at the current solution and the security concerns raised. My first gut reaction is that this feels ok, though.

**Comment by ryan-lane** [comment]
Oh, hah. I raised the concerns, right. Let me re-evaluate my thoughts there.

**Comment by egeland** [comment]
Given that the information sent by the webhook would (still) not include any secrets, adding the possibility to send more is a nice feature-add (and something I've thought about as well 😅 ).

**Comment by edify42** [comment]
[Created a PR to tie into this issue](https://github.com/lyft/confidant/pull/187)

Some use-cases for extra webhooks leaving Confidant:

- Messaging notifications upon secrets being changed in Confidant
- CI triggers to update secrets in apps
- Additional environment support (dev and test) for any Webhook integration above

**Comment by egeland** [comment]
Any movement on this, @ryan-lane ? 😉

**Comment by ryan-lane** [comment]
Hey! Sorry, I've been on sabbatical. I'll be back at the end of the month
but may take a quick look before then.

**Comment by ryan-lane** [comment]
@egeland oh, it looks like the PR comments I left a while back haven't been addressed yet.

**Comment by egeland** [comment]
Suspect @edify42 doesn't use Confidant anymore?

**Comment by edify42** [comment]
Indeed @egeland I don't! - Happy for you to take over this PR if you're keen :)
