### ISSUE TITLE
Support extensible metadata for secrets

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#31]
Using a [JSONAttribute](http://pynamodb.readthedocs.org/en/latest/api.html#pynamodb.attributes.JSONAttribute) in pynamodb, support extensible metadata on secrets. The use-case here is to keep the Confidant server dumb, but allow Confidant clients to be intelligent. For instance, we could have metadata like:

```
mode: 0600
path: /etc/mysecret
user: root
group: root
```

The server is simply storing data, but when the client fetches the secret, it can decide what it wants to do with the secret. In this case it would place the file in /etc/mysecret only accessible by root.

This is partially motivated by https://github.com/lyft/confidant/issues/1.

**Comment by smiller171** [comment]
:+1:

**Comment by smiller171** [comment]
:+1:

**Comment by jewishjeff** [comment]
I would like to work on this, can someone point me in the right direction?

**Comment by ryan-lane** [comment]
@jewishjeff that's awesome, thanks for the help!

We're using pynamodb as an ODM for DynamoDB. The model for this is here:

https://github.com/lyft/confidant/blob/master/confidant/models/credential.py#L32

Otherwise, this is mostly just updating the CRUD operations to accept this attribute and update it accordingly. Unfortunately all the business logic for this is in the routes right now. Here's the four functions that should handle create, read, and update (we never do deletes):

https://github.com/lyft/confidant/blob/master/confidant/routes/v1.py#L290
https://github.com/lyft/confidant/blob/master/confidant/routes/v1.py#L375
https://github.com/lyft/confidant/blob/master/confidant/routes/v1.py#L479
https://github.com/lyft/confidant/blob/master/confidant/routes/v1.py#L549

Let me know if you have any more questions.

**Comment by ryan-lane** [comment]
The backend portion of this is done in v1.1.
