### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by xisafe** [lyft/confidant#311]
(venv) root@kms:/srv/confidant# pip install confidant
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting confidant
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/39/53/ec0af199544c76f0e662f6bf50b365f2ec2063c5042f11c32d95af111e0a/confidant-6.3.0.tar.gz (60 kB)
     |████████████████████████████████| 60 kB 28.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /srv/confidant/venv/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Lo_7dC/confidant/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Lo_7dC/confidant/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-09Aaai
         cwd: /tmp/pip-install-Lo_7dC/confidant/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Lo_7dC/confidant/setup.py", line 16, in <module>
        with open('requirements.in') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.in'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ryan-lane** [comment]
Made a PR that should fix this issue, but you'll need to get the attention of a maintainer (I don't work at Lyft anymore).
