### ISSUE TITLE
Add a lambda to ensure KMS auth key grants are created for IAM roles

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#32]
It's possible to create service mappings without the associated IAM role. This is by design so that it's possible to create credentials and map them to a service before its deployed. The issue here is that when the service is deployed, the grants need to exist for the service to get its credentials. It's possible for an end-user to go to the service page and update the grants, but this should be automated if possible.

We can create a scheduled lambda that runs at a user definable interval that will get all grants from the KMS auth key, then compare them against the service mappings. If a service mapping exists, but grants do not, we can check to see if an IAM role exists and create grants if so.

**Comment by smiller171** [comment]
@ryan-lane Is there an API to do this in a more immediate fassion? ex:

automated script creates IAM roles, creates new services and credentials in confidant, and provisions resources wit h no user interaction

**Comment by ryan-lane** [comment]
Assuming the IAM role is already created all of this is fully automated already. The issue is that KMS won't allow you to create grants for IAM roles that don't exist (it returns an error). We could allow Confidant to create the IAM role if it doesn't exist, but that gives Confidant way more IAM permissions than it needs.

As for an API, we do have endpoints for all of these things, but all of the endpoints necessary to make changes currently require google auth. It's possible to google auth from CLI libraries, but we haven't put much effort into CLI modification clients so far.

**Comment by ryan-lane** [comment]
I think I'm actually going to punt on this in favor of recommending IAM role policy as a solution to this problem (https://github.com/lyft/confidant/issues/53).

Grants still work and continue to be supported, but adding a worker to solve this particular problem probably isn't worth the effort.
