### ISSUE TITLE
Dockerfile vs Dockerhub Image

### ISSUE THREAD

**Issue by jrosco** [lyft/confidant#350]
Hi, 

Looking at the Dockerfile commits in this repo https://github.com/lyft/confidant/commits/master/Dockerfile and the Dockerhub image https://hub.docker.com/layers/lyft/confidant/6.3.0/images/sha256-242e38fe2841baccaaf8714eed1833607deb4a1556808183332a794c4d9050ed?context=explore I can see that there has been some commits after the last published version on Dockerhub 

Is the Dockerfile here pushed elsewhere? 

Looking at the Github actions I can see there was an error for the last commit https://github.com/lyft/confidant/actions/runs/1689047994/jobs/2300187579

**Comment by nerajchand** [comment]
@skiptomyliu - Are there any plans to investigate & resolve the github actions which push to the Dockerhub registry? 
There hasn't been a successful push in the last 3 years and the versions aren't in sync. 

I've seen PR's continue to be merged into master, but each time it fails on that same Build and Deploy task.
