### ISSUE TITLE
Document api

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#39]
The api is currently undocumented. We should add swagger markup.

**Comment by ab** [comment]
:+1: This would also make it easier for people to write clients, of course. :smiley:

**Comment by luispollo** [comment]
+1. I'm currently evaluating Confidant for use in my company, but it's hard to make that choice without the API documentation and/or sample client code.

**Comment by ryan-lane** [comment]
@luispollo in the upcoming 1.1 release of confidant we have a python client:

https://github.com/lyft/confidant/blob/1.1/confidant/client.py
https://github.com/lyft/confidant/blob/1.1/confidant/cli.py

I'm working on docs for 1.1 right now and will try to get some API docs in, ideally soon after the release.

**Comment by luispollo** [comment]
That's great news, @ryan-lane. Thanks for the update!

**Comment by tom-schultz** [comment]
Any movement on this? I'd like to have our applications directly consuming secrets and I can't see Confidant being a good choice for that without API docs.

**Comment by ryan-lane** [comment]
Let me see if I can get a swagger spec out in the next week or so.

**Comment by ryan-lane** [comment]
Thanks for the reminder :)

**Comment by jacohend** [comment]
Is there a swagger spec for this?

I was able to get the server running, but the python client doesn't seem to have any examples (and it's in Python 2), so I wanted to write my own client directly against the confidant APIs, but they don't seem to be documented?

**Comment by ryan-lane** [comment]
I still haven't gotten a chance to add a swagger spec. It's probably easier to go the modernize/2to3 approach you have as a PR in the client for now. I'll try to carve out some time for a spec, since I keep promising it.

**Comment by ryan-lane** [comment]
Full API docs in #269

**Comment by ryan-lane** [comment]
Now documented at: https://lyft.github.io/confidant/api.html
