### ISSUE TITLE
Document IAM role policy configuration for auth and blind credentials

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#53]
It's possible to completely setup KMS auth policy via IAM policy, rather than grants. It's actually a lot easier to maintain and it has a better user experience from the workflow perspective (create credentials, map to a new service in confidant, launch the service in AWS, no need to go back to confidant to create the grants).

We need to update the docs to describe the policy, though, since AWS's KMS docs for IAM policy are basically non-existent and we want very specific policy.

**Comment by ambrons** [comment]
Is this currently documented?  I'm trying to test `Confidant` and having permission problems authenticating via the service.  I setup a new service to use the `confidant-production` IAM role for to/from context just to see what the response would be.  Trying to figure out where to go next.

**Comment by ryan-lane** [comment]
The IAM policy stuff isn't documented at all yet, because it wasn't really recommended in v1.0 since confidant manages KMS grants for the services. In v1.1 I made it possible to disable the grant management.

It'll be easier for us to discuss getting confidant working for you though either IRC (#confidant on Freenode) or through the confidant-users google group (https://groups.google.com/forum/#!forum/confidant-users).

**Comment by ambrons** [comment]
Hey Ryan,

I managed to get everything working with `v1.1` in AWS.  I noticed that it would manage grants.  I was able to see the KMS grants on keys using the `aws cli` however I didn't find that information anywhere else in the console, but perhaps I'm blind.

Have you discussed switching away from grants to... roles?  Or something?  What's the path there?

If you want I'll move this discussion to somewhere else.

**Comment by ryan-lane** [comment]
In 1.1 it's configurable whether or not confidant manages grants. At Lyft we've stopped using the grants in favor of using IAM policies in IAM roles. I'll be adding a section in the advanced docs for 1.1 that describe how this works. The biggest issue here is that it's complicated and AWS doesn't provide any docs for this.

As for the grants, AWS doesn't expose these through the console. You can only access them through the API (or tools like awscli).

**Comment by ryan-lane** [comment]
Added basic docs for service to service auth IAM policy and blind secret IAM policy: https://github.com/lyft/confidant/pull/84.
