### ISSUE TITLE
Setting up OAuth 2.0

### ISSUE THREAD

**Issue by AndreyKrasnov** [lyft/confidant#54]
Hello

I configure oauth2 and obtain OAuth 2.0 credentials: client ID and Client secret.
But in Google Developers Console needed to specify a redirect URI:
"Authorized redirect URIs
For use with requests from a web server. This is the path in your application that users are redirected to after they have authenticated with Google. The path will be appended with the authorization code for access. Must have a protocol. Cannot contain URL fragments or relative paths. Cannot be a public IP address."

Which URI will be correct for user sending back to Confidant app?
Thanks

**Comment by ryan-lane** [comment]
Hey @AndreyKrasnov, I currently use two authorized redirect URIs:

```
https://confidant.example.com/
https://confidant.example.com/v1/login
```
Where confidant.example.com is the domain name of your Confidant web service.

**Comment by ryan-lane** [comment]
I'll update the docs to mention the redirect URIs. Thanks for asking. Let me know if that isn't working for you!

**Comment by AndreyKrasnov** [comment]
Thanks @ryan-lane
