### ISSUE TITLE
Add config option to allow Confidant to generate its own DynamoDB tables.

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#56]
Right now it's possible for Confidant to generate its own tables, but it only occurs if you provide a dynamo url, which is generally only done in development. We should add a config option to control whether or not this occurs, so that even outside of AWS we can allow Confidant to generate its own tables.

**Comment by ryan-lane** [comment]
Fixed in 1.1 via a38e0007a21d302044c664ddf2df8c186edfa6de

**Comment by damaestro** [comment]
@ryan-lane this is great. I was having trouble manually created the dynamodb table and triggering this code path set things up for me correctly and automatically.

**Comment by ryan-lane** [comment]
Awesome. Glad to hear this is working well :)

**Comment by ryan-lane** [comment]
Note that if you're using 1.1 that's it's unreleased and will get changes as they're finished. We run 1.1 internally, so it should always be stable, but you may randomly get new features until we do a proper release.

**Comment by damaestro** [comment]
@ryan-lane I'm actually just toying around with the lyft/confidant:latest docker on elastic beanstalk and got it to create the db for me by defining `DYNAMODB_URL=https://dynamodb.us-west-2.amazonaws.com` and then just removing it and letting EB restart the container. So much better to have it create the db if it doesn't exist IMHO.
