### ISSUE TITLE
Improve Google auth docs

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#58]
The current google auth docs punt on anything related to setting up the application in Google, but those steps aren't really straightforward. We should have some basic docs here, ideally with some screenshots.

**Comment by ryan-lane** [comment]
This is related to some info @damaestro added in the IRC channel. It's necessary to enable the people API for google auth to work, but that's not documented, along with most of the rest of that setup.

**Comment by ambrons** [comment]
So I'm running into the same issue that *Jon* was having with authentication.  I have the Google People API enabled for project / oauth2 client configuration.

While I'm working through figuring out what's going on I found this Google Site:
https://developers.google.com/+/web/api/rest/oauth#authorization-scopes

Which states the scopes you have configured are deprecated.

**Comment by ryan-lane** [comment]
They are indeed deprecated. In the 1.1 branch we're using the updated scopes:

https://github.com/lyft/confidant/blob/1.1/confidant/authnz/userauth.py#L274-L285

That said, the deprecated scopes do work. What issue are you running into?

**Comment by ambrons** [comment]
@ryan-lane I was having an issue getting the google suffix working.  It was throwing a 500 error with "NoneType" attribute when checking against the email address.

I added the `Google People` API to my Google Project and it wasn't fetching.  So I searched all the google APIs for `userinfo` usage.  I switched to the `Google+` API and it's now working.  

As for the deprecated apis yeah Google says they will support them for a while.  Just an FYI, good to see it's updated.

**Comment by damaestro** [comment]
Ah, and I did have to enable G+. Sorry if that was not clear.

**Comment by pnathan** [comment]
Just as an annotation: G+ does have to be enabled. 

Note that the exception should ideally be trapped and the error message from google emitted.  Something like checking for empty user.email and using logging.error would suffice, internal research shows.

**Comment by ryan-lane** [comment]
Added some basic google auth docs: https://github.com/lyft/confidant/pull/84
