### ISSUE TITLE
On Debian 8.4: 1.0.1 pip cryptography fails to install when using SSL 1.0.1t-1+deb8u2

### ISSUE THREAD

**Issue by russmac** [lyft/confidant#81]
Essentially what is reported here, Although it only effects cryptography==1.0.1.

https://github.com/pyca/cryptography/issues/2973

Downgrading SSL packages to '1.0.1k-3+deb8u5' resolves the issue.

**Comment by russmac** [comment]
Do you guys feel its safe to bump cryptography version incrementally until the issue stops occurring? 

https://github.com/lyft/confidant/blob/master/requirements.txt#L30

**Comment by ryan-lane** [comment]
Yep. If you'd like you can send a PR in. We'll need you to sign the CLA if so (https://oss.lyft.com/cla). Otherwise I'll try to get this in tomorrow. Sorry about the issues in Debian, and thanks for the report!
