### ISSUE TITLE
Confidant closes SSL connection during handshake

### ISSUE THREAD

**Issue by BillBrower** [lyft/confidant#87]
By default, Confidant assumes you are running behind an ssl terminator like Amazon's ELB. So Gunicorn is not configured to use ssl and direct, encrypted connections are not possible. That said, this really isn't a bug per se and updating the docs to communicate the assumption that Confidant is running behind an ssl terminator might be the best solution.

Thank you,
Bill

**Comment by ryan-lane** [comment]
Thanks for the report @BillBrower! We probably should support some of the SSL config for gunicorn directly, but at the very minimum we should document that it's not currently supported.
