### ISSUE TITLE
Make auth more modular

### ISSUE THREAD

**Issue by ryan-lane** [lyft/confidant#9]
Web auth is currently limited to google auth with a redis based session storage manager. This should be modular.

**Comment by ryan-lane** [comment]
Since we're looking to make the user authentication modular, it may be a lot easier if we switch to https://github.com/sahat/satellizer which is mostly implemented in angular, with a relatively thin python server side implementation.

**Comment by ryan-lane** [comment]
We should also add SAML support using python-saml. It's maintained by OneLogin, but docs mention it supports any IdP.

**Comment by ab** [comment]
:+1: SAML support would be great! :smile:

**Comment by ryan-lane** [comment]
Progress here in https://github.com/lyft/confidant/pull/52

**Comment by ryan-lane** [comment]
Fixed in https://github.com/lyft/confidant/pull/52
